// ============================================================
// PAYLOAD SANITIZATION INTERLOCK — Phase 18
// XSS Script Tag Stripping, SQL Injection Detection,
// Unauthorized Nested JSON Property Filtration
// Every inbound JSON payload across ALL API routes must pass
// through this automated filtration parser before processing.
// ============================================================

/**
 * XSS Detection Patterns — HTML script tags and event handlers
 */
const XSS_PATTERNS: RegExp[] = [
  /<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,
  /<script[^>]*>/gi,
  /<\/script>/gi,
  /javascript\s*:/gi,
  /on\w+\s*=\s*["'][^"']*["']/gi,  // onclick="...", onload="..."
  /on\w+\s*=\s*[^\s>]*/gi,           // onclick=alert()
  /<iframe\b/gi,
  /<object\b/gi,
  /<embed\b/gi,
  /<form\b/gi,
  /expression\s*\(/gi,  // CSS expression()
  /vbscript\s*:/gi,
  /data\s*:\s*text\/html/gi,
];

/**
 * SQL Injection Detection Patterns
 */
const SQL_INJECTION_PATTERNS: RegExp[] = [
  /union\s+select/gi,
  /union\s+all\s+select/gi,
  /or\s+1\s*=\s*1/gi,
  /and\s+1\s*=\s*1/gi,
  /'\s*or\s+'[^']*'\s*=\s*'/gi,
  /'\s*;\s*drop\s+/gi,
  /'\s*;\s*delete\s+/gi,
  /'\s*;\s*update\s+/gi,
  /'\s*;\s*insert\s+/gi,
  /--\s*$/gm,  // SQL comment terminator
  /\/\*.*\*\//gi,  // SQL block comment
  /xp_cmdshell/gi,
  /exec\s*\(/gi,
  /execute\s*\(/gi,
  /information_schema/gi,
  /sysobjects/gi,
  /syscolumns/gi,
];

/**
 * Maximum allowed nesting depth for JSON payloads
 */
const MAX_NESTING_DEPTH = 5;

/**
 * Maximum allowed string length for any single field value
 */
const MAX_FIELD_LENGTH = 100_000;

/**
 * Allowed top-level property names for common API payloads
 * Any property not in this list is stripped as "unauthorized nested"
 */
const ALLOWED_COMMON_FIELDS = new Set([
  'id', 'code', 'name', 'description', 'email', 'phone', 'address', 'area',
  'password', 'role', 'companyId', 'branchId', 'isActive', 'notes', 'date',
  'dueDate', 'status', 'type', 'quantity', 'rate', 'amount', 'total',
  'discount', 'discountPercent', 'discountAmount', 'vatPercentage', 'vatAmount',
  'grandTotal', 'subTotal', 'paymentOptionId', 'customerId', 'supplierId',
  'productId', 'godownId', 'categoryId', 'brandId', 'colorId', 'unit',
  'costPrice', 'salePrice', 'wholesalePrice', 'dealerPrice', 'openingStock',
  'reorderLevel', 'image', 'reference', 'referenceType', 'batchMode',
  'data', 'lines', 'items', 'search', 'page', 'pageSize', 'limit',
  'actionType', 'targetModel', 'dateFrom', 'dateTo', 'module', 'action',
  'userId', 'userName', 'details', 'ip', 'recordId', 'recordLabel',
  'vatMode', 'method', 'url', 'headers', 'body', 'query',
  'debit', 'credit', 'accountId', 'account', 'particulars',
  'entryCode', 'voucherNo', 'narration', 'totalDebit', 'totalCredit',
  'bankId', 'chequeNo', 'chequeDate', 'referenceNo',
  'mobile', 'website', 'vatNumber', 'tradeLicense', 'binNumber',
  'currencySymbol', 'invoicePrefix', 'thankYouMsg', 'systemNote',
  'showBarcode', 'showPayInWord', 'logoWidth', 'logoHeight',
  'logo', 'brandLogo', 'logoData', 'profileImage',
  'nidFrontImage', 'nidBackImage', 'nidNumber', 'tinNumber',
  'employeeId', 'departmentId', 'designationId', 'joiningDate', 'baseSalary',
  'creditLimit', 'openingBalance', 'openingBalanceType', 'customerType',
  'contactPerson', 'terms', 'coaAccountId',
  'fromBranchId', 'toBranchId', 'transferType', 'fundAmount',
  'fromBankId', 'toBankId', 'authorizedBy', 'authorizedAt',
  'periodStart', 'periodEnd', 'statementType',
  'fiscalYearId', 'isLocked', 'periodMonth', 'periodYear',
  'severity', 'metadata', 'moduleToken', 'httpMethod', 'endpoint',
  'previousState', 'newState', 'diffSummary',
  'threatType', 'blockedAction', 'resolved',
  'isAutoGenerated', 'poNumber', 'invoiceNo', 'sheetNo',
  'deliveryCost', 'cashAmount', 'bankAmount', 'mfsAmount', 'cardAmount',
  'creditOverride', 'overrideBy',
  'hireRate', 'duration', 'installmentAmount', 'downPayment',
  'returnNo', 'reason', 'replacementNo',
  'valudationMethod', 'imeiNumber', 'lastSupplierId', 'segmentId',
  'sizeCapacity', 'gradeLevel', 'salaryBandMin', 'salaryBandMax',
  'gender', 'bloodGroup', 'religion', 'dateOfBirth',
  'fatherName', 'motherName', 'spouseName', 'maritalStatus',
  'presentAddress', 'permanentAddress', 'emergencyContact',
  'bankName', 'bankAccountNo',
  'alternativePhone', 'customerCode', 'supplierCode', 'employeeCode',
  'openingDate', 'isHeadOffice', 'gstNumber', 'managerName',
  'assetCategory', 'purchaseValue', 'salvageValue', 'usefulLifeMonths',
  'depreciationRate', 'accumulatedDepreciation', 'netBookValue',
  'idempotencyKey', 'sharePercentage', 'capitalValue',
  'paymentType', 'chargePercentage', 'cardTypeId', 'paymentOptionId',
  'leaveCode', 'leaveType', 'fromDate', 'toDate', 'totalDays',
  'approvedBy', 'approvedAt',
  'targetAmount', 'month', 'year',
  'batchNumber', 'expiryDate',
  'balanceAmount', 'totalPaid', 'currentStatus', 'nextPaymentDate',
  'installmentNo', 'paidAmount', 'paidDate',
  'creditMemoCode', 'debitNoteCode', 'challanRef',
  'periodDate', 'depreciationAmount', 'notes',
  'verified', 'verificationNotes',
  'sl', 'model', 'color', 'unitPrice', 'mrp', 'payInWord', 'dueInWord',
  'remarks', 'barcodeData', 'printedBy', 'salesPerson', 'invoiceType',
  'balanceStatus', 'branchLocation', 'prevDue', 'totalDue', 'remindDate',
  'ppDiscount', 'adjustment', 'netTotal', 'paidAmount', 'currentDue',
  'customerCode', 'customerName', 'customerMobile', 'customerAddress',
  'invoiceNo', 'invoiceDate',
  'legalText', 'greetingText',
  'preparedBy', 'checkedBy',
  'isVatAuditor', 'vatMaskedFields',
  'filename', 'orientation', 'title', 'subtitle',
  'identifier', 'limit', 'companyId',
]);

export interface SanitizationResult {
  sanitized: boolean;
  threats: string[];
  cleanedPayload: any;
}

/**
 * sanitizeString — Strips XSS script tags and detects SQL injection in a string value
 */
function sanitizeString(value: string): { cleaned: string; threats: string[] } {
  const threats: string[] = [];
  let cleaned = value;

  // Check XSS patterns
  for (const pattern of XSS_PATTERNS) {
    if (pattern.test(cleaned)) {
      threats.push(`XSS_DETECTED: Pattern "${pattern.source}" found in value`);
      // Strip the malicious content
      cleaned = cleaned.replace(pattern, '');
    }
  }

  // Check SQL injection patterns
  for (const pattern of SQL_INJECTION_PATTERNS) {
    if (pattern.test(cleaned)) {
      threats.push(`SQL_INJECTION_DETECTED: Pattern "${pattern.source}" found in value`);
      // Remove the SQL injection attempt
      cleaned = cleaned.replace(pattern, '');
    }
  }

  // Enforce max length
  if (cleaned.length > MAX_FIELD_LENGTH) {
    cleaned = cleaned.substring(0, MAX_FIELD_LENGTH);
    threats.push(`FIELD_TRUNCATED: Value exceeded maximum length of ${MAX_FIELD_LENGTH}`);
  }

  return { cleaned, threats };
}

/**
 * sanitizePayload — Recursively sanitizes an entire JSON payload
 * Strips XSS, SQL injection, unauthorized nested properties
 * Enforces maximum nesting depth
 */
export function sanitizePayload(
  payload: any,
  depth: number = 0,
  path: string = 'root'
): SanitizationResult {
  const threats: string[] = [];

  // Null/undefined/primitive handling
  if (payload === null || payload === undefined) {
    return { sanitized: false, threats: [], cleanedPayload: payload };
  }

  if (typeof payload === 'string') {
    const result = sanitizeString(payload);
    return { sanitized: result.threats.length > 0, threats: result.threats, cleanedPayload: result.cleaned };
  }

  if (typeof payload === 'number' || typeof payload === 'boolean') {
    return { sanitized: false, threats: [], cleanedPayload: payload };
  }

  // Array handling
  if (Array.isArray(payload)) {
    const cleanedArray: any[] = [];
    for (let i = 0; i < payload.length; i++) {
      const result = sanitizePayload(payload[i], depth + 1, `${path}[${i}]`);
      threats.push(...result.threats);
      cleanedArray.push(result.cleanedPayload);
    }
    return { sanitized: threats.length > 0, threats, cleanedPayload: cleanedArray };
  }

  // Object handling
  if (typeof payload === 'object') {
    // Enforce nesting depth
    if (depth > MAX_NESTING_DEPTH) {
      threats.push(`NESTING_DEPTH_EXCEEDED: Object at "${path}" exceeds max depth of ${MAX_NESTING_DEPTH}`);
      return { sanitized: true, threats, cleanedPayload: {} };
    }

    const cleanedObj: Record<string, any> = {};

    for (const [key, value] of Object.entries(payload)) {
      // Strip unauthorized nested properties (at top level, allow common + custom keys)
      // At deeper levels, be more permissive but still sanitize values
      if (depth === 0 && !ALLOWED_COMMON_FIELDS.has(key) && !key.startsWith('_') && !key.match(/^[a-z][a-zA-Z0-9]*$/)) {
        threats.push(`UNAUTHORIZED_PROPERTY: Property "${key}" at "${path}" is not in the allowed field list`);
        continue; // Skip this property
      }

      // Recursively sanitize the value
      const result = sanitizePayload(value, depth + 1, `${path}.${key}`);
      threats.push(...result.threats);
      cleanedObj[key] = result.cleanedPayload;
    }

    return { sanitized: threats.length > 0, threats, cleanedPayload: cleanedObj };
  }

  return { sanitized: false, threats: [], cleanedPayload: payload };
}

/**
 * logSecurityThreat — Records a detected security threat to the SecurityThreatLog table
 */
export async function logSecurityThreat(params: {
  threatType: string;
  ipAddress?: string;
  userAgent?: string;
  endpoint?: string;
  httpMethod?: string;
  payload?: string;
  blockedAction?: string;
  severity?: string;
  companyId?: string;
  userId?: string;
}): Promise<void> {
  try {
    const { db } = await import('@/lib/db');
    await db.securityThreatLog.create({
      data: {
        threatType: params.threatType,
        ipAddress: params.ipAddress || null,
        endpoint: params.endpoint || null,
        payload: params.payload ? String(params.payload).substring(0, 5000) : null,
        notes: [params.userAgent, params.httpMethod, params.blockedAction].filter(Boolean).join(' | ') || null,
        severity: params.severity || 'HIGH',
        companyId: params.companyId || null,
      },
    });
  } catch (error) {
    console.error('[SecurityThreatLogger] Failed to log threat:', error);
  }
}
